
services:
  frontend:
    build:
      context: ./media-scraper-frontend 
    ports:
      - "3000:3000"  
    volumes:
      - ./media-scraper-frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./media-scraper-backend  
    ports:
      - "3001:3001"  
    environment:
      - NODE_ENV=development
    volumes:
      - ./media-scraper-backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: tonyle
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" 
