services:
  frontend:
    build:
      context: ./media-scraper-frontend 
    ports:
      - "3000:3000"  
    volumes:
      - ./media-scraper-frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./media-scraper-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://tonyle:password@db:5432/mydb
    volumes:
      - ./media-scraper-backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: postgres
    environment:
      POSTGRES_USER: tonyle
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: {}